### ISSUE TITLE
hi，发现您的《多型与虚拟》少了第四章，不知道您发现了没有的

### ISSUE THREAD

**Issue by MingYueRuYa** [tianshilei1992/polymorphsim_in_cpp#1]

**Comment by shiltian** [comment]
您好，确实是少第四章的，侯老师给我的就是这个版本。

**Comment by MingYueRuYa** [comment]
哎呀，好可惜的。这本书写的是非常好的，所以我特意去打印店打印了一份的。看完之后就发现了少了第四章，我也用电子邮件的方式联系过侯捷老师的，但是没有响应的。不过还是非常谢谢您了。而且侯老师的网站都不能访问了。
