### ISSUE TITLE
简体中文版能否共享一下，谢谢。

### ISSUE THREAD

**Issue by lilucpp** [tianshilei1992/polymorphsim_in_cpp#2]

**Comment by lilucpp** [comment]
淘宝、京东、亚马逊上都没有纸质的，请问一下你知道怎么能买到吗？另外简体中文能否共享一下？谢谢

**Comment by shiltian** [comment]
@lilucpp 你好，我没有简体中文版的，只有侯老师发给我的繁体中文原版的。简体字我之前有翻译，但是由于时间原因只做了序言…没有做下去。

**Comment by lilucpp** [comment]
@tianshilei1992 了解了。多谢。
