### ISSUE TITLE
lack of chapter 4 Why Polymorphism

### ISSUE THREAD

**Issue by YMoose** [tianshilei1992/polymorphsim_in_cpp#3]
您好，原书的pdf，应该是漏了第四章，pdf第211页按照原书目录应该是第四章，但是pdf是第五章，同时查看pdf页面可以明显发现pdf总页数少于原书目录最大页数。

**Comment by shiltian** [comment]
感谢反馈。这个书是侯老师直接发给我的，我没有做任何的修改，因此我也解决不了这个问题。

**Comment by YMoose** [comment]
哦~原来是这样，确实我在网上看到别的版本也是少了的。谢谢您及时的回复。之后我再和侯老师联系一下好了，请问他的电子邮箱是否还是书上写的 jjhou@ccca.nctu.edu.tw 这个？

**Comment by shiltian** [comment]
不是这个，我不知道直接在这里贴上侯老师的 email 好不好，你可以邮件联系我我告诉你。
